id: P476F6176
initial_creation_type: ocr
source_metadata:
  volumes:
    9f0f37b43dda411b9262ff61aa2e51e0:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: སྐུ་དང་གསུང་དང་ཐུགས་རབ་ཏུ་གནས་པ།
      total_pages: 1953
      volume_number: 27
